import type { PolicyAnnouncement, CompanyProfile, PolicyApplication, MatchResult } from '@/types';

export const MOCK_POLICIES: PolicyAnnouncement[] = [
  {
    id: 'pol_001',
    title: '2026년 중소기업 정책자금(혁신성장자금)',
    organization: '중소벤처기업부',
    category: 'funding',
    target_audience: '중소기업, 소상공인',
    eligibility: '업력 3년 이상, 매출 10억 미만 중소기업',
    support_scale: '최대 10억원 (연 2.0% 이내)',
    application_start: '2026-03-01',
    application_end: '2026-06-30',
    required_documents: ['사업계획서', '재무제표', '사업자등록증', '법인등기부등본', '납세증명서'],
    description: '혁신성장을 위한 시설자금 및 운전자금 지원. 스마트공장, 디지털 전환, 탄소중립 관련 설비투자 우대.',
    detail_url: 'https://www.bizinfo.go.kr',
    status: 'open',
    difficulty: 'medium',
    preparation_period: 14,
    source: '기업마당',
    created_at: '2026-02-15',
    updated_at: '2026-02-15',
  },
  {
    id: 'pol_002',
    title: '2026년 창업성장기술개발사업(TIPS)',
    organization: '중소벤처기업부',
    category: 'rnd',
    target_audience: '기술창업기업',
    eligibility: '업력 7년 이내 기술기반 창업기업, TIPS 운영사 추천 필수',
    support_scale: 'R&D 최대 5억원 + 창업사업화 1억원',
    application_start: '2026-04-01',
    application_end: '2026-05-31',
    required_documents: ['사업계획서', 'IR 자료', '기술설명서', '운영사 추천서', '특허 관련 서류'],
    description: '민간 투자 주도형 기술창업 지원. 엔젤투자 연계, 해외 진출 지원 포함.',
    detail_url: 'https://www.k-startup.go.kr',
    status: 'upcoming',
    difficulty: 'hard',
    preparation_period: 30,
    source: 'K-Startup',
    created_at: '2026-02-20',
    updated_at: '2026-02-20',
  },
  {
    id: 'pol_003',
    title: '2026년 벤처기업 확인 (벤처인증)',
    organization: '중소벤처기업부',
    category: 'certification',
    target_audience: '중소기업',
    eligibility: '기술성 또는 사업성이 우수한 중소기업',
    support_scale: '세제혜택, 입찰가점, 자금 우대금리',
    application_start: '2026-01-01',
    application_end: '2026-12-31',
    required_documents: ['벤처확인 신청서', '재무제표', '기술사업계획서', '특허증명서'],
    description: '벤처기업 확인을 통한 다양한 혜택 제공. 기술보증기금 또는 중소기업진흥공단 평가.',
    detail_url: 'https://www.venturein.or.kr',
    status: 'open',
    difficulty: 'medium',
    preparation_period: 21,
    source: '벤처인',
    created_at: '2026-01-01',
    updated_at: '2026-01-01',
  },
  {
    id: 'pol_004',
    title: '2026년 수출바우처 사업',
    organization: '한국무역협회',
    category: 'export',
    target_audience: '수출 중소기업',
    eligibility: '직전년도 수출실적 보유 중소기업, 수출유망기업',
    support_scale: '최대 1억원 바우처 (자부담 30%)',
    application_start: '2026-03-15',
    application_end: '2026-04-30',
    required_documents: ['수출바우처 신청서', '수출실적 증명', '사업자등록증', '사업계획서'],
    description: '해외마케팅, 통번역, 해외인증, 물류 등 수출 관련 서비스 이용 바우처 지원.',
    detail_url: 'https://www.exportvoucher.com',
    status: 'upcoming',
    difficulty: 'easy',
    preparation_period: 7,
    source: '기업마당',
    created_at: '2026-02-25',
    updated_at: '2026-02-25',
  },
  {
    id: 'pol_005',
    title: '2026년 스마트공장 구축 지원사업',
    organization: '중소벤처기업부',
    category: 'consulting',
    target_audience: '제조 중소기업',
    eligibility: '제조업 영위 중소기업, 스마트공장 미도입 기업 우대',
    support_scale: '기초 최대 5천만원, 고도화 최대 1.5억원',
    application_start: '2026-02-01',
    application_end: '2026-04-15',
    required_documents: ['신청서', '사업계획서', '공장등록증', '재무제표'],
    description: 'ICT·IoT 기반 스마트공장 구축 지원. 기초-고도화 단계별 지원.',
    detail_url: 'https://www.smart-factory.kr',
    status: 'open',
    difficulty: 'medium',
    preparation_period: 14,
    source: '스마트공장',
    created_at: '2026-01-20',
    updated_at: '2026-01-20',
  },
  {
    id: 'pol_006',
    title: '2026년 청년창업사관학교',
    organization: '중소벤처기업부',
    category: 'education',
    target_audience: '만 39세 이하 (예비)창업자',
    eligibility: '만 39세 이하, 창업 3년 이내 또는 예비창업자',
    support_scale: '교육+멘토링+사업화자금 최대 1억원',
    application_start: '2026-03-01',
    application_end: '2026-03-31',
    required_documents: ['입교신청서', '사업계획서', '주민등록등본', '졸업증명서'],
    description: '청년 창업자 대상 집중 보육 프로그램. 창업 교육, 멘토링, 사업화 자금 지원.',
    detail_url: 'https://start.kosmes.or.kr',
    status: 'open',
    difficulty: 'medium',
    preparation_period: 14,
    source: 'K-Startup',
    created_at: '2026-02-10',
    updated_at: '2026-02-10',
  },
  {
    id: 'pol_007',
    title: '2026년 일자리 안정자금 지원',
    organization: '고용노동부',
    category: 'manpower',
    target_audience: '30인 미만 사업장',
    eligibility: '30인 미만 사업장, 최저임금 120% 이하 근로자 고용',
    support_scale: '근로자 1인당 월 최대 13만원',
    application_start: '2026-01-01',
    application_end: '2026-12-31',
    required_documents: ['지원신청서', '사업자등록증', '근로계약서', '급여대장'],
    description: '최저임금 인상에 따른 소규모 사업장 인건비 부담 경감 지원.',
    detail_url: 'https://www.jobstability.go.kr',
    status: 'open',
    difficulty: 'easy',
    preparation_period: 7,
    source: '고용노동부',
    created_at: '2026-01-01',
    updated_at: '2026-01-01',
  },
  {
    id: 'pol_008',
    title: '2026년 내판로 개척 지원사업',
    organization: '중소벤처기업부',
    category: 'marketing',
    target_audience: '중소기업, 소상공인',
    eligibility: '우수 제품 보유 중소기업',
    support_scale: '전시회 참가비, 온라인 판로 지원 최대 3천만원',
    application_start: '2026-04-01',
    application_end: '2026-05-15',
    required_documents: ['신청서', '제품 카탈로그', '사업자등록증', '매출증빙'],
    description: '국내 판로 확대를 위한 전시회, 온라인 마케팅, 홈쇼핑 입점 등 지원.',
    detail_url: 'https://www.bizinfo.go.kr',
    status: 'upcoming',
    difficulty: 'easy',
    preparation_period: 10,
    source: '기업마당',
    created_at: '2026-03-01',
    updated_at: '2026-03-01',
  },
];

export const MOCK_COMPANIES: CompanyProfile[] = [
  {
    id: 'comp1',
    name: '(주)테크이노베이션',
    business_number: '123-45-67890',
    ceo_name: '김철수',
    industry: 'IT/소프트웨어',
    industry_code: 'J62',
    established_date: '2022-06-15',
    employee_count: 15,
    annual_revenue: 800000000,
    location: '서울특별시 강남구',
    company_type: 'startup',
    growth_stage: 'early',
    certifications: ['벤처기업', 'ISO 27001'],
    technologies: ['AI/ML', '클라우드', 'SaaS'],
    previous_supports: ['2025년 창업성장기술개발사업'],
    financial_data: {
      revenue: 800000000,
      operating_profit: 50000000,
      net_income: 30000000,
      total_assets: 500000000,
      total_debt: 200000000,
      growth_rate: 45,
      year: 2025,
    },
    created_at: '2026-01-01',
    updated_at: '2026-01-01',
  },
  {
    id: 'comp2',
    name: '(주)그린에너지솔루션',
    business_number: '234-56-78901',
    ceo_name: '박영희',
    industry: '신재생에너지',
    industry_code: 'D35',
    established_date: '2019-03-20',
    employee_count: 45,
    annual_revenue: 3500000000,
    location: '경기도 성남시',
    company_type: 'venture',
    growth_stage: 'growth',
    certifications: ['벤처기업', '이노비즈', 'ISO 14001'],
    technologies: ['태양광', 'ESS', '에너지관리'],
    previous_supports: ['2024년 스마트공장 구축', '2025년 수출바우처'],
    financial_data: {
      revenue: 3500000000,
      operating_profit: 350000000,
      net_income: 250000000,
      total_assets: 2000000000,
      total_debt: 800000000,
      growth_rate: 30,
      year: 2025,
    },
    created_at: '2026-01-01',
    updated_at: '2026-01-01',
  },
  {
    id: 'comp3',
    name: '맛있는빵집',
    business_number: '345-67-89012',
    ceo_name: '이민수',
    industry: '식품제조',
    industry_code: 'C10',
    established_date: '2024-01-10',
    employee_count: 5,
    annual_revenue: 150000000,
    location: '서울특별시 마포구',
    company_type: 'small',
    growth_stage: 'early',
    certifications: [],
    technologies: [],
    previous_supports: [],
    financial_data: {
      revenue: 150000000,
      operating_profit: 15000000,
      net_income: 10000000,
      total_assets: 80000000,
      total_debt: 30000000,
      growth_rate: 20,
      year: 2025,
    },
    created_at: '2026-01-01',
    updated_at: '2026-01-01',
  },
];

export const MOCK_MATCH_RESULTS: MatchResult[] = [
  {
    id: 'match_001',
    company_id: 'comp1',
    policy_id: 'pol_001',
    policy: MOCK_POLICIES[0],
    match_score: 85,
    match_reasons: ['업력 3년 이상 충족', 'IT/소프트웨어 업종 우대', '매출 10억 미만 조건 충족', '디지털 전환 관련 기업'],
    eligibility_status: 'eligible',
    recommended_priority: 'high',
    preparation_tips: ['최근 3년 재무제표 준비', '디지털 전환 성과 중심 사업계획서 작성', '기술혁신 실적 정리'],
    estimated_approval_rate: 35,
    created_at: '2026-03-01',
  },
  {
    id: 'match_002',
    company_id: 'comp1',
    policy_id: 'pol_002',
    policy: MOCK_POLICIES[1],
    match_score: 92,
    match_reasons: ['기술창업기업 조건 충족', 'AI/ML 기술 보유', '업력 7년 이내', '이전 창업지원 수혜 이력'],
    eligibility_status: 'eligible',
    recommended_priority: 'high',
    preparation_tips: ['TIPS 운영사 사전 접촉 필수', 'IR 자료 및 기술 데모 준비', '특허 출원/등록 현황 정리'],
    estimated_approval_rate: 25,
    created_at: '2026-03-01',
  },
  {
    id: 'match_003',
    company_id: 'comp1',
    policy_id: 'pol_006',
    policy: MOCK_POLICIES[5],
    match_score: 60,
    match_reasons: ['창업 3년 이내 조건 충족', '기술기반 창업'],
    eligibility_status: 'likely',
    recommended_priority: 'medium',
    preparation_tips: ['대표자 연령 확인 필요 (만 39세 이하)', '입교 시 전일제 참여 가능 여부 확인'],
    estimated_approval_rate: 20,
    created_at: '2026-03-01',
  },
  {
    id: 'match_004',
    company_id: 'comp2',
    policy_id: 'pol_004',
    policy: MOCK_POLICIES[3],
    match_score: 88,
    match_reasons: ['수출실적 보유', '벤처기업 인증', '수출바우처 활용 이력 (갱신 가능)'],
    eligibility_status: 'eligible',
    recommended_priority: 'high',
    preparation_tips: ['전년도 수출실적 증빙 준비', '해외 마케팅 계획 수립', '바우처 활용 계획서 작성'],
    estimated_approval_rate: 45,
    created_at: '2026-03-01',
  },
  {
    id: 'match_005',
    company_id: 'comp2',
    policy_id: 'pol_005',
    policy: MOCK_POLICIES[4],
    match_score: 75,
    match_reasons: ['제조관련 설비 운영', '스마트공장 고도화 대상', '이전 기초단계 수혜'],
    eligibility_status: 'eligible',
    recommended_priority: 'medium',
    preparation_tips: ['기존 스마트공장 운영 현황 정리', '고도화 목표 및 기대효과 작성'],
    estimated_approval_rate: 40,
    created_at: '2026-03-01',
  },
  {
    id: 'match_006',
    company_id: 'comp3',
    policy_id: 'pol_007',
    policy: MOCK_POLICIES[6],
    match_score: 95,
    match_reasons: ['30인 미만 사업장', '소규모 제조업', '최저임금 기준 충족 가능성 높음'],
    eligibility_status: 'eligible',
    recommended_priority: 'high',
    preparation_tips: ['근로계약서 및 급여대장 정리', '4대보험 가입 확인'],
    estimated_approval_rate: 80,
    created_at: '2026-03-01',
  },
];

export const MOCK_APPLICATIONS: PolicyApplication[] = [
  {
    id: 'app_001',
    company_id: 'comp1',
    policy_id: 'pol_001',
    policy: MOCK_POLICIES[0],
    status: 'preparing',
    documents: [
      { name: '사업계획서', status: 'ready' },
      { name: '재무제표', status: 'ready' },
      { name: '사업자등록증', status: 'ready' },
      { name: '법인등기부등본', status: 'pending' },
      { name: '납세증명서', status: 'pending' },
    ],
    timeline: [
      { date: '2026-03-01', event: '공고 확인', description: '정책자금 공고 확인 및 검토 시작' },
      { date: '2026-03-03', event: '서류 준비 시작', description: '사업계획서 및 재무제표 준비' },
    ],
    notes: '디지털 전환 관련 내용 강조 필요',
    created_at: '2026-03-01',
    updated_at: '2026-03-03',
  },
  {
    id: 'app_002',
    company_id: 'comp2',
    policy_id: 'pol_005',
    policy: MOCK_POLICIES[4],
    status: 'applied',
    applied_date: '2026-02-20',
    documents: [
      { name: '신청서', status: 'submitted' },
      { name: '사업계획서', status: 'submitted' },
      { name: '공장등록증', status: 'submitted' },
      { name: '재무제표', status: 'submitted' },
    ],
    timeline: [
      { date: '2026-02-05', event: '공고 확인', description: '스마트공장 구축 지원사업 확인' },
      { date: '2026-02-10', event: '서류 준비', description: '신청서류 일체 준비 완료' },
      { date: '2026-02-20', event: '신청 완료', description: '온라인 신청 및 서류 제출 완료' },
      { date: '2026-03-01', event: '서류 심사', description: '서류 심사 진행 중' },
    ],
    notes: '고도화 단계 신청. 기존 기초단계 성과 보고서 첨부.',
    result: 'pending',
    created_at: '2026-02-05',
    updated_at: '2026-03-01',
  },
];
